#
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[workspace]
members = [".", "./macros", "./agones"]

[workspace.dependencies]
kube = { version = "0.83.0", features = ["derive", "runtime", "rustls-tls", "client"], default-features = false }
k8s-openapi = { version = "0.18.0", features = ["v1_25", "schemars"] }
tokio = { version = "1.28.1", features = ["rt-multi-thread", "fs", "signal", "test-util", "parking_lot", "tracing"] }
base64 = "0.21.0"

[package]
name = "quilkin"
version = "0.7.0-dev"
authors = ["Mark Mandel <markmandel@google.com>", "Ifeanyi Ubah <ifeanyi.ubah@embark-studios.com>", "Erin Power <erin.power@embark-studios.com>"]
license = "Apache-2.0"
description = "Quilkin is a non-transparent UDP proxy specifically designed for use with large scale multiplayer dedicated game server deployments, to ensure security, access control, telemetry data, metrics and more."
homepage = "https://github.com/googleforgames/quilkin"
repository = "https://github.com/googleforgames/quilkin"
readme = "README.md"
keywords = ["proxy", "game-server", "game-development", "networking", "multiplayer"]
categories = ["game-development", "network-programming"]
edition = "2021"
exclude = ["docs", "build", "examples", "image"]

[[bench]]
name = "throughput"
harness = false
test = true

[dependencies]
# Local
quilkin-macros = { version = "0.7.0-dev", path = "./macros" }

# Crates.io
arc-swap = { version = "1.6.0", features = ["serde"] }
async-stream = "0.3.5"
base64.workspace = true
base64-serde = "0.7.0"
bytes = { version = "1.4.0", features = ["serde"] }
cached = "0.43.0"
chrono = "0.4.24"
clap = { version = "4.3.0", features = ["cargo", "derive", "env"] }
dashmap = { version = "5.4.0", features = ["serde"] }
dirs2 = "3.0.1"
either = "1.8.1"
enum-map = "2.5.0"
eyre = "0.6.8"
futures = "0.3.28"
hyper = { version = "0.14.26", features = ["http2"] }
hyper-rustls = { version = "0.24.0", features = ["http2", "webpki-roots"] }
ipnetwork = "0.20.0"
k8s-openapi.workspace = true
maxminddb = "0.23.0"
notify = "6.0.0"
num_cpus = "1.15.0"
once_cell = "1.17.1"
parking_lot = "0.12.1"
prometheus = { version = "0.13.3", default-features = false }
prost = "0.11.9"
prost-types = "0.11.9"
rand = "0.8.5"
regex = "1.8.2"
schemars = { version = "0.8.12", features = ["chrono", "bytes", "url"] }
serde = { version = "1.0.163", features = ["derive", "rc"] }
serde_json = "1.0.96"
serde_regex = "1.1.0"
serde_stacker = "0.1.8"
serde_yaml = "0.9.21"
snap = "1.1.0"
socket2 = { version = "0.5.3", features = ["all"] }
stable-eyre = "0.2.2"
thiserror = "1.0.40"
tokio.workspace = true
tokio-stream = { version = "0.1.14", features = ["sync"] }
tonic = "0.9.2"
tracing = "0.1.37"
tracing-futures = { version = "0.2.5", features = ["futures-03"] }
tracing-subscriber = { version = "0.3.17", features = ["json", "env-filter"] }
tryhard = "0.5.0"
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.3.3", default-features = false, features = ["v4"] }
lasso = { version = "0.7.2", features = ["multi-threaded"] }
kube.workspace = true
trust-dns-resolver = { version = "0.21.0", features = ["tokio", "tokio-rustls", "dns-over-https-rustls"] }
async-trait = "0.1.68"
nom = "7.1.3"

[target.'cfg(target_os = "linux")'.dependencies]
sys-info = "0.9.1"

[dev-dependencies]
regex = "1.8.2"
criterion = { version = "0.5.0", features = ["html_reports"] }
once_cell = "1.17.1"
tracing-test = "0.2.4"
pretty_assertions = "1.3.0"
tempfile = "3.5.0"

[build-dependencies]
tonic-build = { version = "0.9.2", default_features = false, features = ["transport", "prost"] }
prost-build = "0.11.9"
built = { version = "0.6.0", features = ["git2"] }
protobuf-src = { version = "1.1.0", optional = true }

[features]
default = ["vendor-protoc"]
instrument = []
vendor-protoc = ["dep:protobuf-src"]
