#
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[workspace]
members = [".", "./macros"]

[package]
name = "quilkin"
version = "0.3.0-dev"
authors = ["Mark Mandel <markmandel@google.com>", "Ifeanyi Ubah <ifeanyi.ubah@embark-studios.com>"]
license = "Apache-2.0"
description = "Quilkin is a non-transparent UDP proxy specifically designed for use with large scale multiplayer dedicated game server deployments, to ensure security, access control, telemetry data, metrics and more."
homepage = "https://github.com/googleforgames/quilkin"
repository = "https://github.com/googleforgames/quilkin"
readme = "README.md"
keywords = ["proxy", "game-server", "game-development", "networking", "multiplayer"]
categories = ["game-development", "network-programming"]
edition = "2021"
exclude = ["docs", "build", "examples", "image"]

[[bench]]
name = "throughput"
harness = false
test = true

[dependencies]
# Local
quilkin-macros = { version = "0.3.0-dev", path = "./macros" }

# Crates.io
base64 = "0.13.0"
base64-serde = "0.6.1"
bytes = "1.1.0"
clap = "2.33.3"
dashmap = "4.0.2"
either = "1.6.1"
hyper = "0.14.13"
num_cpus = "1.13.0"
parking_lot = "0.11.2"
prometheus = { version = "0.13.0", default-features = false }
prost = "=0.8"
prost-types = "=0.8"
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = "1.0.68"
serde_yaml = "0.8.21"
slog = "2.7.0"
slog-async = "2.7.0"
slog-json = "2.4.0"
slog-term = "2.8.0"
snap = "1.0.5"
tokio = { version = "1.12.0", features = ["rt-multi-thread", "signal", "test-util", "parking_lot"] }
tokio-stream = "0.1.7"
tonic = "0.5.2"
tracing = {version = "0.1"}
tracing-subscriber = {version = "0.2"}
uuid = { version = "0.8.2", default-features = false, features = ["v4"] }
thiserror = "1.0.30"
tryhard = "0.4.0"
eyre = "0.6.5"
stable-eyre = "0.2.2"
ipnetwork = "0.18.0"

[target.'cfg(target_os = "linux")'.dependencies]
sys-info = "0.9.0"

[dev-dependencies]
regex = "1.5.4"
criterion = { version = "0.3.5", features = ["html_reports"] }
once_cell = "1.8.0"
tracing-test = "0.1"

[build-dependencies]
tonic-build = { version = "0.5.2", default_features = false, features = ["transport", "prost"] }
# Locked to 0.8 to match `tonic-build`'s `prost-build`.
prost-build = "=0.8"

[features]
instrument = []
