#
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
]
all-features = true

[advisories]
unmaintained = 'workspace'
yanked = 'deny'
ignore = [
]

[bans]
deny = [
    { crate = "openssl-sys", use-instead = "rustls" },
    { crate = "openssl", use-instead = "rustls" },
    { crate = "aws-lc-sys", use-instead = "ring" },
    { crate = "cmake", use-instead = "cc" },
    { crate = "chrono", use-instead = "time", wrappers = [
        "k8s-openapi",
        "kube-client",
        "kube-core",
        "kube-leader-election",
    ] },
]
multiple-versions = "deny"
skip = [
    { crate = "object@0.32.2", reason = "transitive dependency due to backtrace, backtrace is updated, but stable-eyre using a feature that doesn't exist any longer, and can't update, sigh" },
    { crate = "hashbrown@0.14.5", reason = "many crates use this old version" },
    { crate = "getrandom@0.2.16", reason = "ring" },
]
skip-tree = [
    { crate = "thiserror@1.0.69", reason = "many crates use this old version" },
]

[[bans.features]]
name = "rustls"
deny = ["aws_lc_rs", "aws-lc-rs"]

[[bans.features]]
name = "tokio-rustls"
deny = ["aws-lc-rs"]

[[bans.features]]
name = "rustls-webpki"
deny = ["aws-lc-rs"]

[bans.workspace-dependencies]
unused = 'allow'

# This section is considered when running `cargo deny check licenses`
# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
allow = ["Apache-2.0", "MIT", "ISC", "BSD-3-Clause", "Unicode-3.0"]
exceptions = [
    { crate = "adler32", allow = ["Zlib"] },
    { crate = "foldhash", allow = ["Zlib"] },
    # This license should not really be used for code, but here we are
    { crate = "notify", allow = ["CC0-1.0"] },
    { crate = "webpki-roots", allow = ["CDLA-Permissive-2.0"] },
]
