[package]
name = "xds-example"
version = "0.1.0"
edition = "2021"

[dependencies]
xds = { path = "../../crates/xds" }
eyre = "0.6"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dependencies.tokio]
version = "1.0"

[workspace]
