#
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Pool of Quilkin proxies, tied to the
# xDS control plane in xds-control-plane.yaml
#

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: proxy
  name: quilkin-proxies
spec:
  replicas: 3
  selector:
    matchLabels:
      role: proxy
  template:
    metadata:
      labels:
        role: proxy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: quilkin
          image: us-docker.pkg.dev/quilkin/release/quilkin:0.6.0
          args: ["proxy", "--management-server", "http://quilkin-manage-agones:80"]
          env:
            - name: RUST_LOG
              value: info #,quilkin=trace
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /live
              port: 8000
              scheme: HTTP
          ports:
            - containerPort: 7777
              protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: quilkin-proxies
spec:
  ports:
    - port: 7777
      protocol: UDP
      targetPort: 7777
  selector:
    role: proxy
  type: LoadBalancer
