apiVersion: v1
kind: Pod
metadata:
  name: echo-server
spec:
  containers:
  - name: echo-server
    image: fortio/fortio
    ports:
    - containerPort: 8078
      hostPort: 8078
    args: ["udp-echo"]

