linters:
   enable:
   - gofmt
   - goimports
   - revive
   - bodyclose
   - deadcode
   - dupl
   - exportloopref
   - gocritic
   - gocyclo
   - govet
   - megacheck
   - misspell
   - nakedret
   - staticcheck
   - structcheck
   - unconvert
   - unparam
